name: web_dex # Use `lowercase_with_underscores` for package names
description: komodo atomicDEX web wallet

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.9.2+0

environment:
  sdk: ^3.8.1
  flutter: ^3.32.5

dependencies:
  ## ---- Flutter SDK

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  ## ---- Local packages by Komodo team

  app_theme:
    path: "./app_theme"

  komodo_ui_kit:
    path: packages/komodo_ui_kit

  komodo_persistence_layer:
    path: packages/komodo_persistence_layer

  komodo_cex_market_data:
    # path: sdk/packages/komodo_cex_market_data # Requires symlink to the SDK in the root of the project
    git:
      url: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter.git
      path: packages/komodo_cex_market_data
      ref: dev

  ## ---- KomodoPlatform pub.dev packages (First-party)

  dragon_logs: 1.1.0

  ## ---- Dart.dev, Flutter.dev
  args: ^2.7.0 # dart.dev
  flutter_markdown: ^0.7.7 # flutter.dev
  http: 1.4.0 # dart.dev
  intl: 0.20.2 # dart.dev
  js: ">=0.6.7 <=0.7.2" # dart.dev
  url_launcher: 6.3.1 # flutter.dev
  crypto: 3.0.6 # dart.dev
  cross_file: 0.3.4+2 # flutter.dev
  video_player: ^2.9.5 # flutter.dev
  logging: 1.3.0

  ## ---- google.com

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  window_size:
    git:
      url: https://github.com/KomodoPlatform/flutter-desktop-embedding
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8

  ## ---- firebase.google.com

  # Upgraded Firebase, needs secure code review

  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0

  ## ---- Fluttercommunity.dev

  # does not require review, since hosted and git versions are the same
  equatable: 2.0.7 # sdk depends on hosted version, and not from git

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106 (Outdated)
  package_info_plus: 8.3.0

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106 (Outdated)
  share_plus: 10.1.4

  ## ---- 3d party

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106 (Outdated)
  encrypt: 5.0.3

  flutter_svg: 2.0.17

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106 (Outdated)
  qr_flutter: 4.1.0

  easy_localization: 3.0.7+1 # last reviewed 3.0.2 via https://github.com/KomodoPlatform/komodo-wallet/pull/1106

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106 (Outdated)
  universal_html: 2.2.4

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  hive: ^2.2.3 # Changed from git to pub.dev because git dependencies are not allowed in published packages

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106
  hive_flutter: ^1.1.0 # Changed from git to pub.dev because git dependencies are not allowed in published packages

  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/1106 (Outdated)
  badges: 3.1.2

  flutter_slidable: 4.0.0

  # Embedded web view
  # Approved via https://github.com/KomodoPlatform/komodo-wallet/pull/3
  flutter_inappwebview: 6.1.5 # Android, iOS, macOS, Web (currently broke, open issue)

  # Newly added, not yet reviewed
  formz: 0.8.0

  # TODO: review required
  dragon_charts_flutter: 0.1.1-dev.1
  bloc_concurrency: 0.3.0
  file_picker: ^10.0.0

  # TODO: review required - SDK integration
  path_provider: 2.1.5 # flutter.dev
  shared_preferences: ^2.5.3 # flutter.dev
  decimal: 3.2.1 # transitive dependency that is required to fix breaking changes in rational package
  rational: 2.2.3 # sdk depends on decimal ^3.0.2, which depends on rational ^2.0.0
  uuid: 4.5.1 # sdk depends on this version
  flutter_bloc: ^9.1.0 # sdk depends on this version, and hosted instead of git reference
  get_it: ^8.0.3 # sdk depends on this version, and hosted instead of git reference
  komodo_defi_sdk: # TODO: change to pub.dev version?
    # path: sdk/packages/komodo_defi_sdk # Requires symlink to the SDK in the root of the project
    git:
      url: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter.git
      path: packages/komodo_defi_sdk
      ref: dev

  komodo_defi_types:
    # path: sdk/packages/komodo_defi_types # Requires symlink to the SDK in the root of the project
    git:
      url: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter.git
      path: packages/komodo_defi_types
      ref: dev

  komodo_ui:
    # path: sdk/packages/komodo_ui # Requires symlink to the SDK in the root of the project
    git:
      url: https://github.com/KomodoPlatform/komodo-defi-sdk-flutter.git
      path: packages/komodo_ui
      ref: dev
  feedback: ^3.1.0
  ntp: ^2.0.0
  flutter_window_close: ^1.2.0

dev_dependencies:
  integration_test: # SDK
    sdk: flutter
  test: ^1.24.1 # dart.dev

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0 # flutter.dev

dependency_overrides:
  # Temporary until Flutter's pinned version is updated
  intl: ^0.20.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/custom_icons/16px/
    - assets/logo/
    - assets/fonts/
    - assets/flags/
    - assets/ui_icons/
    - assets/others/
    - assets/translations/
    - assets/nav_icons/mobile/
    - assets/nav_icons/desktop/dark/
    - assets/nav_icons/desktop/light/
    - assets/blockchain_icons/svg/32px/
    - assets/custom_icons/
    - assets/web_pages/
    - assets/fiat/fiat_icons_square/
    - assets/fiat/providers/
    - assets/packages/flutter_inappwebview_web/assets/web/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/fallback_fonts/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
          weight: 400

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
