name: app_theme
description: App theme.
version: 0.0.1
# homepage:

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.32.5

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.8 # flutter.dev
